
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.toamod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.toamod.item.WoodenSwordItem;
import net.mcreator.toamod.item.WoodenKeyItem;
import net.mcreator.toamod.item.WoodenHandleItem;
import net.mcreator.toamod.item.TomatoItem;
import net.mcreator.toamod.item.TheDarkBladeItem;
import net.mcreator.toamod.item.SweatRoastedChickenItem;
import net.mcreator.toamod.item.StrawberryItem;
import net.mcreator.toamod.item.SteakAndChipsItem;
import net.mcreator.toamod.item.SpicySpicedChilliItem;
import net.mcreator.toamod.item.SilverKeyItem;
import net.mcreator.toamod.item.ScrollWeaknessItem;
import net.mcreator.toamod.item.ScrollLightningStrikeItem;
import net.mcreator.toamod.item.ScrollBigSliceItem;
import net.mcreator.toamod.item.ScrollBerserkItem;
import net.mcreator.toamod.item.RawTurkeyItem;
import net.mcreator.toamod.item.RawRagoutRabbitItem;
import net.mcreator.toamod.item.RawMuttonItem;
import net.mcreator.toamod.item.RawGrouperItem;
import net.mcreator.toamod.item.RawCrabItem;
import net.mcreator.toamod.item.RabbitRagoutItem;
import net.mcreator.toamod.item.PureIronItem;
import net.mcreator.toamod.item.PureGoldItem;
import net.mcreator.toamod.item.OnionItem;
import net.mcreator.toamod.item.ObsidianItem;
import net.mcreator.toamod.item.ObsidianHandleItem;
import net.mcreator.toamod.item.MetalHandleItem;
import net.mcreator.toamod.item.MetalGuardItem;
import net.mcreator.toamod.item.MangoItem;
import net.mcreator.toamod.item.MagmaShardItem;
import net.mcreator.toamod.item.MagmaGuardItem;
import net.mcreator.toamod.item.MagicDustItem;
import net.mcreator.toamod.item.LeekItem;
import net.mcreator.toamod.item.LambPlateItem;
import net.mcreator.toamod.item.JadeSwordItem;
import net.mcreator.toamod.item.JadeItem;
import net.mcreator.toamod.item.JadeGuardItem;
import net.mcreator.toamod.item.JadeBladeItem;
import net.mcreator.toamod.item.IronSwordItem;
import net.mcreator.toamod.item.IronBladeItem;
import net.mcreator.toamod.item.HardenedIronSwordItem;
import net.mcreator.toamod.item.HardenedIronBladeItem;
import net.mcreator.toamod.item.HamSoupItem;
import net.mcreator.toamod.item.GrapesItem;
import net.mcreator.toamod.item.GoldenSwordItem;
import net.mcreator.toamod.item.GoldenKeyItem;
import net.mcreator.toamod.item.GoldenHeartItem;
import net.mcreator.toamod.item.GoldBladeItem;
import net.mcreator.toamod.item.FlameSwordItem;
import net.mcreator.toamod.item.FishMealItem;
import net.mcreator.toamod.item.FieryHeartItem;
import net.mcreator.toamod.item.EnrichtedMagmaShardItem;
import net.mcreator.toamod.item.EnrichtedCristalItem;
import net.mcreator.toamod.item.EnchtantedBookItem;
import net.mcreator.toamod.item.EggItem;
import net.mcreator.toamod.item.DragonSlayerItem;
import net.mcreator.toamod.item.DragonSlayerBladeItem;
import net.mcreator.toamod.item.DeathsDanceItem;
import net.mcreator.toamod.item.DarkBladeItem;
import net.mcreator.toamod.item.CupOfCoffeeItem;
import net.mcreator.toamod.item.CristalSwordItem;
import net.mcreator.toamod.item.CristalShardItem;
import net.mcreator.toamod.item.CristalItem;
import net.mcreator.toamod.item.CristalBladeItem;
import net.mcreator.toamod.item.CranberryItem;
import net.mcreator.toamod.item.CorItem;
import net.mcreator.toamod.item.CookedTurkeyItem;
import net.mcreator.toamod.item.CookedRagoutRabbitItem;
import net.mcreator.toamod.item.CookedMuttonItem;
import net.mcreator.toamod.item.CoffeeBeansItem;
import net.mcreator.toamod.item.CoalItem;
import net.mcreator.toamod.item.ChocolateStrawberryItem;
import net.mcreator.toamod.item.ChocolateItem;
import net.mcreator.toamod.item.ChilliItem;
import net.mcreator.toamod.item.ChickenGumboItem;
import net.mcreator.toamod.item.BroccoliItem;
import net.mcreator.toamod.item.BookSharpness9Item;
import net.mcreator.toamod.item.BookSharpness8Item;
import net.mcreator.toamod.item.BookSharpness7Item;
import net.mcreator.toamod.item.BookSharpness6Item;
import net.mcreator.toamod.item.BookSharpness5Item;
import net.mcreator.toamod.item.BookSharpness4Item;
import net.mcreator.toamod.item.BookSharpness3Item;
import net.mcreator.toamod.item.BookSharpness2Item;
import net.mcreator.toamod.item.BookSharpness1Item;
import net.mcreator.toamod.item.BookSharpness10Item;
import net.mcreator.toamod.item.BookLifesteel3Item;
import net.mcreator.toamod.item.BookLifesteel2Item;
import net.mcreator.toamod.item.BookLifesteel1Item;
import net.mcreator.toamod.item.BookExecuting5Item;
import net.mcreator.toamod.item.BookExecuting4Item;
import net.mcreator.toamod.item.BookExecuting3Item;
import net.mcreator.toamod.item.BookExecuting2Item;
import net.mcreator.toamod.item.BookExecuting1Item;
import net.mcreator.toamod.item.BlueberryItem;
import net.mcreator.toamod.item.BananaSplitItem;
import net.mcreator.toamod.item.AncientWarhammerItem;
import net.mcreator.toamod.item.AncientGuardianWarhammerItem;
import net.mcreator.toamod.ToamodMod;

public class ToamodModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ToamodMod.MODID);
	public static final RegistryObject<Item> COAL = REGISTRY.register("coal", () -> new CoalItem());
	public static final RegistryObject<Item> CRISTAL_SHARD = REGISTRY.register("cristal_shard", () -> new CristalShardItem());
	public static final RegistryObject<Item> CRISTAL = REGISTRY.register("cristal", () -> new CristalItem());
	public static final RegistryObject<Item> ENRICHTED_CRISTAL = REGISTRY.register("enrichted_cristal", () -> new EnrichtedCristalItem());
	public static final RegistryObject<Item> JADE = REGISTRY.register("jade", () -> new JadeItem());
	public static final RegistryObject<Item> GOLDEN_HEART = REGISTRY.register("golden_heart", () -> new GoldenHeartItem());
	public static final RegistryObject<Item> FIERY_HEART = REGISTRY.register("fiery_heart", () -> new FieryHeartItem());
	public static final RegistryObject<Item> MAGMA_SHARD = REGISTRY.register("magma_shard", () -> new MagmaShardItem());
	public static final RegistryObject<Item> ENRICHTED_MAGMA_SHARD = REGISTRY.register("enrichted_magma_shard", () -> new EnrichtedMagmaShardItem());
	public static final RegistryObject<Item> OBSIDIAN = REGISTRY.register("obsidian", () -> new ObsidianItem());
	public static final RegistryObject<Item> WOODEN_KEY = REGISTRY.register("wooden_key", () -> new WoodenKeyItem());
	public static final RegistryObject<Item> SILVER_KEY = REGISTRY.register("silver_key", () -> new SilverKeyItem());
	public static final RegistryObject<Item> GOLDEN_KEY = REGISTRY.register("golden_key", () -> new GoldenKeyItem());
	public static final RegistryObject<Item> COR = REGISTRY.register("cor", () -> new CorItem());
	public static final RegistryObject<Item> MAGIC_DUST = REGISTRY.register("magic_dust", () -> new MagicDustItem());
	public static final RegistryObject<Item> ORE_RESPAWN_STONE = block(ToamodModBlocks.ORE_RESPAWN_STONE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> COAL_ORE = block(ToamodModBlocks.COAL_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> IRON_ORE = block(ToamodModBlocks.IRON_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> GOLD_ORE = block(ToamodModBlocks.GOLD_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CRISTAL_ORE = block(ToamodModBlocks.CRISTAL_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> JADE_ORE = block(ToamodModBlocks.JADE_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> MAGMA = block(ToamodModBlocks.MAGMA, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CURSED_OBSIDIAN = block(ToamodModBlocks.CURSED_OBSIDIAN, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CHEST_NORMAL = block(ToamodModBlocks.CHEST_NORMAL, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CHEST_EPIC = block(ToamodModBlocks.CHEST_EPIC, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CHEST_LEGENDARY = block(ToamodModBlocks.CHEST_LEGENDARY, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CONTROL_BARRIER = block(ToamodModBlocks.CONTROL_BARRIER, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> UPGRADING_TABLE = block(ToamodModBlocks.UPGRADING_TABLE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> COOKING_TABLE = block(ToamodModBlocks.COOKING_TABLE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> ARMORY_TABLE = block(ToamodModBlocks.ARMORY_TABLE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> WEAPON_TABLE = block(ToamodModBlocks.WEAPON_TABLE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> WOODEN_SWORD = REGISTRY.register("wooden_sword", () -> new WoodenSwordItem());
	public static final RegistryObject<Item> IRON_SWORD = REGISTRY.register("iron_sword", () -> new IronSwordItem());
	public static final RegistryObject<Item> GOLDEN_SWORD = REGISTRY.register("golden_sword", () -> new GoldenSwordItem());
	public static final RegistryObject<Item> CRISTAL_SWORD = REGISTRY.register("cristal_sword", () -> new CristalSwordItem());
	public static final RegistryObject<Item> JADE_SWORD = REGISTRY.register("jade_sword", () -> new JadeSwordItem());
	public static final RegistryObject<Item> FLAME_SWORD = REGISTRY.register("flame_sword", () -> new FlameSwordItem());
	public static final RegistryObject<Item> DEATHS_DANCE = REGISTRY.register("deaths_dance", () -> new DeathsDanceItem());
	public static final RegistryObject<Item> DRAGON_SLAYER = REGISTRY.register("dragon_slayer", () -> new DragonSlayerItem());
	public static final RegistryObject<Item> THE_DARK_BLADE = REGISTRY.register("the_dark_blade", () -> new TheDarkBladeItem());
	public static final RegistryObject<Item> ANCIENT_GUARDIAN_WARHAMMER = REGISTRY.register("ancient_guardian_warhammer",
			() -> new AncientGuardianWarhammerItem());
	public static final RegistryObject<Item> SCROLL_LIGHTNING_STRIKE = REGISTRY.register("scroll_lightning_strike",
			() -> new ScrollLightningStrikeItem());
	public static final RegistryObject<Item> SCROLL_WEAKNESS = REGISTRY.register("scroll_weakness", () -> new ScrollWeaknessItem());
	public static final RegistryObject<Item> SCROLL_BERSERK = REGISTRY.register("scroll_berserk", () -> new ScrollBerserkItem());
	public static final RegistryObject<Item> SCROLL_BIG_SLICE = REGISTRY.register("scroll_big_slice", () -> new ScrollBigSliceItem());
	public static final RegistryObject<Item> ENCHTANTED_BOOK = REGISTRY.register("enchtanted_book", () -> new EnchtantedBookItem());
	public static final RegistryObject<Item> BOOK_EXECUTING_1 = REGISTRY.register("book_executing_1", () -> new BookExecuting1Item());
	public static final RegistryObject<Item> BOOK_EXECUTING_2 = REGISTRY.register("book_executing_2", () -> new BookExecuting2Item());
	public static final RegistryObject<Item> BOOK_EXECUTING_3 = REGISTRY.register("book_executing_3", () -> new BookExecuting3Item());
	public static final RegistryObject<Item> BOOK_EXECUTING_4 = REGISTRY.register("book_executing_4", () -> new BookExecuting4Item());
	public static final RegistryObject<Item> BOOK_EXECUTING_5 = REGISTRY.register("book_executing_5", () -> new BookExecuting5Item());
	public static final RegistryObject<Item> BOOK_LIFESTEEL_1 = REGISTRY.register("book_lifesteel_1", () -> new BookLifesteel1Item());
	public static final RegistryObject<Item> BOOK_LIFESTEEL_2 = REGISTRY.register("book_lifesteel_2", () -> new BookLifesteel2Item());
	public static final RegistryObject<Item> BOOK_LIFESTEEL_3 = REGISTRY.register("book_lifesteel_3", () -> new BookLifesteel3Item());
	public static final RegistryObject<Item> BOOK_SHARPNESS_1 = REGISTRY.register("book_sharpness_1", () -> new BookSharpness1Item());
	public static final RegistryObject<Item> BOOK_SHARPNESS_2 = REGISTRY.register("book_sharpness_2", () -> new BookSharpness2Item());
	public static final RegistryObject<Item> BOOK_SHARPNESS_3 = REGISTRY.register("book_sharpness_3", () -> new BookSharpness3Item());
	public static final RegistryObject<Item> BOOK_SHARPNESS_4 = REGISTRY.register("book_sharpness_4", () -> new BookSharpness4Item());
	public static final RegistryObject<Item> BOOK_SHARPNESS_5 = REGISTRY.register("book_sharpness_5", () -> new BookSharpness5Item());
	public static final RegistryObject<Item> BOOK_SHARPNESS_6 = REGISTRY.register("book_sharpness_6", () -> new BookSharpness6Item());
	public static final RegistryObject<Item> BOOK_SHARPNESS_7 = REGISTRY.register("book_sharpness_7", () -> new BookSharpness7Item());
	public static final RegistryObject<Item> BOOK_SHARPNESS_8 = REGISTRY.register("book_sharpness_8", () -> new BookSharpness8Item());
	public static final RegistryObject<Item> BOOK_SHARPNESS_9 = REGISTRY.register("book_sharpness_9", () -> new BookSharpness9Item());
	public static final RegistryObject<Item> BOOK_SHARPNESS_10 = REGISTRY.register("book_sharpness_10", () -> new BookSharpness10Item());
	public static final RegistryObject<Item> EGG = REGISTRY.register("egg", () -> new EggItem());
	public static final RegistryObject<Item> ONION = REGISTRY.register("onion", () -> new OnionItem());
	public static final RegistryObject<Item> LEEK = REGISTRY.register("leek", () -> new LeekItem());
	public static final RegistryObject<Item> BROCCOLI = REGISTRY.register("broccoli", () -> new BroccoliItem());
	public static final RegistryObject<Item> CHILLI = REGISTRY.register("chilli", () -> new ChilliItem());
	public static final RegistryObject<Item> TOMATO = REGISTRY.register("tomato", () -> new TomatoItem());
	public static final RegistryObject<Item> GRAPES = REGISTRY.register("grapes", () -> new GrapesItem());
	public static final RegistryObject<Item> STRAWBERRY = REGISTRY.register("strawberry", () -> new StrawberryItem());
	public static final RegistryObject<Item> BLUEBERRY = REGISTRY.register("blueberry", () -> new BlueberryItem());
	public static final RegistryObject<Item> CRANBERRY = REGISTRY.register("cranberry", () -> new CranberryItem());
	public static final RegistryObject<Item> MANGO = REGISTRY.register("mango", () -> new MangoItem());
	public static final RegistryObject<Item> COFFEE_BEANS = REGISTRY.register("coffee_beans", () -> new CoffeeBeansItem());
	public static final RegistryObject<Item> CUP_OF_COFFEE = REGISTRY.register("cup_of_coffee", () -> new CupOfCoffeeItem());
	public static final RegistryObject<Item> CHOCOLATE = REGISTRY.register("chocolate", () -> new ChocolateItem());
	public static final RegistryObject<Item> CHOCOLATE_STRAWBERRY = REGISTRY.register("chocolate_strawberry", () -> new ChocolateStrawberryItem());
	public static final RegistryObject<Item> RAW_MUTTON = REGISTRY.register("raw_mutton", () -> new RawMuttonItem());
	public static final RegistryObject<Item> COOKED_MUTTON = REGISTRY.register("cooked_mutton", () -> new CookedMuttonItem());
	public static final RegistryObject<Item> RAW_TURKEY = REGISTRY.register("raw_turkey", () -> new RawTurkeyItem());
	public static final RegistryObject<Item> COOKED_TURKEY = REGISTRY.register("cooked_turkey", () -> new CookedTurkeyItem());
	public static final RegistryObject<Item> RAW_RAGOUT_RABBIT = REGISTRY.register("raw_ragout_rabbit", () -> new RawRagoutRabbitItem());
	public static final RegistryObject<Item> COOKED_RAGOUT_RABBIT = REGISTRY.register("cooked_ragout_rabbit", () -> new CookedRagoutRabbitItem());
	public static final RegistryObject<Item> RAW_CRAB = REGISTRY.register("raw_crab", () -> new RawCrabItem());
	public static final RegistryObject<Item> RAW_GROUPER = REGISTRY.register("raw_grouper", () -> new RawGrouperItem());
	public static final RegistryObject<Item> CHICKEN_GUMBO = REGISTRY.register("chicken_gumbo", () -> new ChickenGumboItem());
	public static final RegistryObject<Item> HAM_SOUP = REGISTRY.register("ham_soup", () -> new HamSoupItem());
	public static final RegistryObject<Item> RABBIT_RAGOUT = REGISTRY.register("rabbit_ragout", () -> new RabbitRagoutItem());
	public static final RegistryObject<Item> SPICY_SPICED_CHILLI = REGISTRY.register("spicy_spiced_chilli", () -> new SpicySpicedChilliItem());
	public static final RegistryObject<Item> STEAK_AND_CHIPS = REGISTRY.register("steak_and_chips", () -> new SteakAndChipsItem());
	public static final RegistryObject<Item> FISH_MEAL = REGISTRY.register("fish_meal", () -> new FishMealItem());
	public static final RegistryObject<Item> LAMB_PLATE = REGISTRY.register("lamb_plate", () -> new LambPlateItem());
	public static final RegistryObject<Item> SWEAT_ROASTED_CHICKEN = REGISTRY.register("sweat_roasted_chicken", () -> new SweatRoastedChickenItem());
	public static final RegistryObject<Item> BANANA_SPLIT = REGISTRY.register("banana_split", () -> new BananaSplitItem());
	public static final RegistryObject<Item> PURE_GOLD = REGISTRY.register("pure_gold", () -> new PureGoldItem());
	public static final RegistryObject<Item> WOODEN_HANDLE = REGISTRY.register("wooden_handle", () -> new WoodenHandleItem());
	public static final RegistryObject<Item> METAL_HANDLE = REGISTRY.register("metal_handle", () -> new MetalHandleItem());
	public static final RegistryObject<Item> PURE_IRON = REGISTRY.register("pure_iron", () -> new PureIronItem());
	public static final RegistryObject<Item> OBSIDIAN_HANDLE = REGISTRY.register("obsidian_handle", () -> new ObsidianHandleItem());
	public static final RegistryObject<Item> METAL_GUARD = REGISTRY.register("metal_guard", () -> new MetalGuardItem());
	public static final RegistryObject<Item> JADE_GUARD = REGISTRY.register("jade_guard", () -> new JadeGuardItem());
	public static final RegistryObject<Item> MAGMA_GUARD = REGISTRY.register("magma_guard", () -> new MagmaGuardItem());
	public static final RegistryObject<Item> LOG = block(ToamodModBlocks.LOG, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> HARDENED_IRON_SWORD = REGISTRY.register("hardened_iron_sword", () -> new HardenedIronSwordItem());
	public static final RegistryObject<Item> IRON_BLADE = REGISTRY.register("iron_blade", () -> new IronBladeItem());
	public static final RegistryObject<Item> HARDENED_IRON_BLADE = REGISTRY.register("hardened_iron_blade", () -> new HardenedIronBladeItem());
	public static final RegistryObject<Item> GOLD_BLADE = REGISTRY.register("gold_blade", () -> new GoldBladeItem());
	public static final RegistryObject<Item> CRISTAL_BLADE = REGISTRY.register("cristal_blade", () -> new CristalBladeItem());
	public static final RegistryObject<Item> JADE_BLADE = REGISTRY.register("jade_blade", () -> new JadeBladeItem());
	public static final RegistryObject<Item> DRAGON_SLAYER_BLADE = REGISTRY.register("dragon_slayer_blade", () -> new DragonSlayerBladeItem());
	public static final RegistryObject<Item> DARK_BLADE = REGISTRY.register("dark_blade", () -> new DarkBladeItem());
	public static final RegistryObject<Item> ANCIENT_WARHAMMER = REGISTRY.register("ancient_warhammer", () -> new AncientWarhammerItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
