
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.toamod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.toamod.item.WoodenSwordItem;
import net.mcreator.toamod.item.WoodArmorItem;
import net.mcreator.toamod.item.WarmBreakfastItem;
import net.mcreator.toamod.item.TuskItem;
import net.mcreator.toamod.item.TomatoItem;
import net.mcreator.toamod.item.TheDarkBladeItem;
import net.mcreator.toamod.item.TacoItem;
import net.mcreator.toamod.item.SweetHamItem;
import net.mcreator.toamod.item.SweatRoastedChickenItem;
import net.mcreator.toamod.item.SuperEnchantmentBookItem;
import net.mcreator.toamod.item.StrawberryItem;
import net.mcreator.toamod.item.SteakAndChipsItem;
import net.mcreator.toamod.item.StatIconWISItem;
import net.mcreator.toamod.item.StatIconMRItem;
import net.mcreator.toamod.item.StatIconMPItem;
import net.mcreator.toamod.item.StatIconMINFItem;
import net.mcreator.toamod.item.StatIconMFItem;
import net.mcreator.toamod.item.StatIconMANAItem;
import net.mcreator.toamod.item.StatIconHPItem;
import net.mcreator.toamod.item.StatIconCRCDItem;
import net.mcreator.toamod.item.StatIconARItem;
import net.mcreator.toamod.item.StatIconADItem;
import net.mcreator.toamod.item.StarfallHyperionItem;
import net.mcreator.toamod.item.SpicySpicedChilliItem;
import net.mcreator.toamod.item.SilverKeyItem;
import net.mcreator.toamod.item.ScaldrisHyperionItem;
import net.mcreator.toamod.item.RuneUncommanItem;
import net.mcreator.toamod.item.RuneRareItem;
import net.mcreator.toamod.item.RuneMythicItem;
import net.mcreator.toamod.item.RuneLegendaryItem;
import net.mcreator.toamod.item.RuneFragmentsItem;
import net.mcreator.toamod.item.RuneEpicItem;
import net.mcreator.toamod.item.RuneCommanItem;
import net.mcreator.toamod.item.RoughRuneFragmentItem;
import net.mcreator.toamod.item.RefinedTuskItem;
import net.mcreator.toamod.item.RedGoblinScaleItem;
import net.mcreator.toamod.item.RedCrystalItem;
import net.mcreator.toamod.item.RedCrystalClusterItem;
import net.mcreator.toamod.item.RedCopperItem;
import net.mcreator.toamod.item.RedCopperBarItem;
import net.mcreator.toamod.item.RawTurkeyItem;
import net.mcreator.toamod.item.RawRagoutRabbitItem;
import net.mcreator.toamod.item.RawMuttonItem;
import net.mcreator.toamod.item.RawHamItem;
import net.mcreator.toamod.item.RawGrouperItem;
import net.mcreator.toamod.item.RawCrabItem;
import net.mcreator.toamod.item.RawBeefItem;
import net.mcreator.toamod.item.RabbitRagoutItem;
import net.mcreator.toamod.item.PureIronItem;
import net.mcreator.toamod.item.PureGoldItem;
import net.mcreator.toamod.item.PureCrystalItem;
import net.mcreator.toamod.item.PristineRuneFragmentItem;
import net.mcreator.toamod.item.PowerCatalyst5Item;
import net.mcreator.toamod.item.PowerCatalyst4Item;
import net.mcreator.toamod.item.PowerCatalyst3Item;
import net.mcreator.toamod.item.PowerCatalyst2Item;
import net.mcreator.toamod.item.PowerCatalyst1Item;
import net.mcreator.toamod.item.PlayerRecipesItemItem;
import net.mcreator.toamod.item.PerfectRuneFragmentItem;
import net.mcreator.toamod.item.OnionItem;
import net.mcreator.toamod.item.ObsidianItem;
import net.mcreator.toamod.item.NearPerfectRuneFragmentItem;
import net.mcreator.toamod.item.MythicRuneScrollItem;
import net.mcreator.toamod.item.MithrilSwordItem;
import net.mcreator.toamod.item.MithrilItem;
import net.mcreator.toamod.item.MithrilBarItem;
import net.mcreator.toamod.item.MangoItem;
import net.mcreator.toamod.item.ManaStoneItem;
import net.mcreator.toamod.item.MagicDustItem;
import net.mcreator.toamod.item.LeekItem;
import net.mcreator.toamod.item.LambPlateItem;
import net.mcreator.toamod.item.JadeSwordItem;
import net.mcreator.toamod.item.JadeItem;
import net.mcreator.toamod.item.JadeBarItem;
import net.mcreator.toamod.item.JadeArmorItem;
import net.mcreator.toamod.item.IronSwordItem;
import net.mcreator.toamod.item.IronBarItem;
import net.mcreator.toamod.item.IronArmorItem;
import net.mcreator.toamod.item.IllfangsCutlassItem;
import net.mcreator.toamod.item.HardenedIronSwordItem;
import net.mcreator.toamod.item.HardenedIronArmorItem;
import net.mcreator.toamod.item.HamSoupItem;
import net.mcreator.toamod.item.GrapesItem;
import net.mcreator.toamod.item.GoldenSwordItem;
import net.mcreator.toamod.item.GoldenKeyItem;
import net.mcreator.toamod.item.GoldenHeartItem;
import net.mcreator.toamod.item.GoldBarItem;
import net.mcreator.toamod.item.GoldArmorItem;
import net.mcreator.toamod.item.GoblinEggSpicesItem;
import net.mcreator.toamod.item.GoblinEggItem;
import net.mcreator.toamod.item.GemstoneTopazItem;
import net.mcreator.toamod.item.GemstoneTanzaniteItem;
import net.mcreator.toamod.item.GemstoneSaphireItem;
import net.mcreator.toamod.item.GemstoneRubyItem;
import net.mcreator.toamod.item.GemstonePearlItem;
import net.mcreator.toamod.item.GemstoneOpalItem;
import net.mcreator.toamod.item.GemstoneEmeraldItem;
import net.mcreator.toamod.item.GemstoneDiamondItem;
import net.mcreator.toamod.item.GemstoneAquamarineItem;
import net.mcreator.toamod.item.GemstoneAmethystItem;
import net.mcreator.toamod.item.GemstoneAmberItem;
import net.mcreator.toamod.item.FriedGoblinEggItem;
import net.mcreator.toamod.item.FootlongItem;
import net.mcreator.toamod.item.FlawlessRuneFragmentItem;
import net.mcreator.toamod.item.FlawedRuneFragmentItem;
import net.mcreator.toamod.item.FlameSwordItem;
import net.mcreator.toamod.item.FishMealItem;
import net.mcreator.toamod.item.FineRuneFragmentItem;
import net.mcreator.toamod.item.FieryHeartItem;
import net.mcreator.toamod.item.ExquisiteRuneFragmentItem;
import net.mcreator.toamod.item.EnchantmentBookItem;
import net.mcreator.toamod.item.EnchBookItem;
import net.mcreator.toamod.item.EmptyBookItem;
import net.mcreator.toamod.item.DwarfsHymnItem;
import net.mcreator.toamod.item.DropOfBloodItem;
import net.mcreator.toamod.item.DragonSlayerItem;
import net.mcreator.toamod.item.DragonArmorItem;
import net.mcreator.toamod.item.DeathsDanceItem;
import net.mcreator.toamod.item.DarkRedDyeItem;
import net.mcreator.toamod.item.CupOfCoffeeItem;
import net.mcreator.toamod.item.CrystalShardItem;
import net.mcreator.toamod.item.CrystalItem;
import net.mcreator.toamod.item.CrystalClusterItem;
import net.mcreator.toamod.item.CristalSwordItem;
import net.mcreator.toamod.item.CristalArmorItem;
import net.mcreator.toamod.item.CranberryItem;
import net.mcreator.toamod.item.CorItem;
import net.mcreator.toamod.item.CookingSkillItemItem;
import net.mcreator.toamod.item.CookedTurkeyItem;
import net.mcreator.toamod.item.CookedRagoutRabbitItem;
import net.mcreator.toamod.item.CookedMuttonItem;
import net.mcreator.toamod.item.CookedBeefItem;
import net.mcreator.toamod.item.CoffeeBeansItem;
import net.mcreator.toamod.item.CoalItem;
import net.mcreator.toamod.item.CoalBarItem;
import net.mcreator.toamod.item.ChocolateStrawberryItem;
import net.mcreator.toamod.item.ChocolateItem;
import net.mcreator.toamod.item.ChilliItem;
import net.mcreator.toamod.item.ChickenGumboItem;
import net.mcreator.toamod.item.BurningSoulItem;
import net.mcreator.toamod.item.BroccoliItem;
import net.mcreator.toamod.item.BossKeyTier5Item;
import net.mcreator.toamod.item.BossKeyTier4Item;
import net.mcreator.toamod.item.BossKeyTier3Item;
import net.mcreator.toamod.item.BossKeyTier2Item;
import net.mcreator.toamod.item.BossKeyTier1Item;
import net.mcreator.toamod.item.BlueberryItem;
import net.mcreator.toamod.item.BlueCopperItem;
import net.mcreator.toamod.item.BlueCopperBarItem;
import net.mcreator.toamod.item.BananaSplitItem;
import net.mcreator.toamod.item.ArtefactsItemItem;
import net.mcreator.toamod.item.AncientGuardianWarhammerItem;
import net.mcreator.toamod.ToamodMod;

public class ToamodModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ToamodMod.MODID);
	public static final RegistryObject<Item> OBSIDIAN = REGISTRY.register("obsidian", () -> new ObsidianItem());
	public static final RegistryObject<Item> COAL = REGISTRY.register("coal", () -> new CoalItem());
	public static final RegistryObject<Item> JADE = REGISTRY.register("jade", () -> new JadeItem());
	public static final RegistryObject<Item> GOLDEN_HEART = REGISTRY.register("golden_heart", () -> new GoldenHeartItem());
	public static final RegistryObject<Item> FIERY_HEART = REGISTRY.register("fiery_heart", () -> new FieryHeartItem());
	public static final RegistryObject<Item> CURSED_OBSIDIAN = block(ToamodModBlocks.CURSED_OBSIDIAN);
	public static final RegistryObject<Item> MAGMA = block(ToamodModBlocks.MAGMA);
	public static final RegistryObject<Item> COAL_ORE = block(ToamodModBlocks.COAL_ORE);
	public static final RegistryObject<Item> IRON_ORE = block(ToamodModBlocks.IRON_ORE);
	public static final RegistryObject<Item> GOLD_ORE = block(ToamodModBlocks.GOLD_ORE);
	public static final RegistryObject<Item> JADE_ORE = block(ToamodModBlocks.JADE_ORE);
	public static final RegistryObject<Item> CRISTAL_ORE = block(ToamodModBlocks.CRISTAL_ORE);
	public static final RegistryObject<Item> CRISTAL_SWORD = REGISTRY.register("cristal_sword", () -> new CristalSwordItem());
	public static final RegistryObject<Item> WOODEN_SWORD = REGISTRY.register("wooden_sword", () -> new WoodenSwordItem());
	public static final RegistryObject<Item> IRON_SWORD = REGISTRY.register("iron_sword", () -> new IronSwordItem());
	public static final RegistryObject<Item> GOLDEN_SWORD = REGISTRY.register("golden_sword", () -> new GoldenSwordItem());
	public static final RegistryObject<Item> CHEST_NORMAL = block(ToamodModBlocks.CHEST_NORMAL);
	public static final RegistryObject<Item> CHEST_EPIC = block(ToamodModBlocks.CHEST_EPIC);
	public static final RegistryObject<Item> SILVER_KEY = REGISTRY.register("silver_key", () -> new SilverKeyItem());
	public static final RegistryObject<Item> GOLDEN_KEY = REGISTRY.register("golden_key", () -> new GoldenKeyItem());
	public static final RegistryObject<Item> CHEST_LEGENDARY = block(ToamodModBlocks.CHEST_LEGENDARY);
	public static final RegistryObject<Item> COR = REGISTRY.register("cor", () -> new CorItem());
	public static final RegistryObject<Item> ORE_RESPAWN_STONE = block(ToamodModBlocks.ORE_RESPAWN_STONE);
	public static final RegistryObject<Item> MAGIC_DUST = REGISTRY.register("magic_dust", () -> new MagicDustItem());
	public static final RegistryObject<Item> CONTROL_BARRIER = block(ToamodModBlocks.CONTROL_BARRIER);
	public static final RegistryObject<Item> LEEK = REGISTRY.register("leek", () -> new LeekItem());
	public static final RegistryObject<Item> GRAPES = REGISTRY.register("grapes", () -> new GrapesItem());
	public static final RegistryObject<Item> STRAWBERRY = REGISTRY.register("strawberry", () -> new StrawberryItem());
	public static final RegistryObject<Item> BLUEBERRY = REGISTRY.register("blueberry", () -> new BlueberryItem());
	public static final RegistryObject<Item> CRANBERRY = REGISTRY.register("cranberry", () -> new CranberryItem());
	public static final RegistryObject<Item> BROCCOLI = REGISTRY.register("broccoli", () -> new BroccoliItem());
	public static final RegistryObject<Item> COFFEE_BEANS = REGISTRY.register("coffee_beans", () -> new CoffeeBeansItem());
	public static final RegistryObject<Item> CUP_OF_COFFEE = REGISTRY.register("cup_of_coffee", () -> new CupOfCoffeeItem());
	public static final RegistryObject<Item> RAW_MUTTON = REGISTRY.register("raw_mutton", () -> new RawMuttonItem());
	public static final RegistryObject<Item> COOKED_MUTTON = REGISTRY.register("cooked_mutton", () -> new CookedMuttonItem());
	public static final RegistryObject<Item> RAW_TURKEY = REGISTRY.register("raw_turkey", () -> new RawTurkeyItem());
	public static final RegistryObject<Item> COOKED_TURKEY = REGISTRY.register("cooked_turkey", () -> new CookedTurkeyItem());
	public static final RegistryObject<Item> RAW_RAGOUT_RABBIT = REGISTRY.register("raw_ragout_rabbit", () -> new RawRagoutRabbitItem());
	public static final RegistryObject<Item> COOKED_RAGOUT_RABBIT = REGISTRY.register("cooked_ragout_rabbit", () -> new CookedRagoutRabbitItem());
	public static final RegistryObject<Item> RAW_CRAB = REGISTRY.register("raw_crab", () -> new RawCrabItem());
	public static final RegistryObject<Item> RAW_GROUPER = REGISTRY.register("raw_grouper", () -> new RawGrouperItem());
	public static final RegistryObject<Item> TOMATO = REGISTRY.register("tomato", () -> new TomatoItem());
	public static final RegistryObject<Item> ONION = REGISTRY.register("onion", () -> new OnionItem());
	public static final RegistryObject<Item> CHICKEN_GUMBO = REGISTRY.register("chicken_gumbo", () -> new ChickenGumboItem());
	public static final RegistryObject<Item> STEAK_AND_CHIPS = REGISTRY.register("steak_and_chips", () -> new SteakAndChipsItem());
	public static final RegistryObject<Item> SPICY_SPICED_CHILLI = REGISTRY.register("spicy_spiced_chilli", () -> new SpicySpicedChilliItem());
	public static final RegistryObject<Item> RABBIT_RAGOUT = REGISTRY.register("rabbit_ragout", () -> new RabbitRagoutItem());
	public static final RegistryObject<Item> FISH_MEAL = REGISTRY.register("fish_meal", () -> new FishMealItem());
	public static final RegistryObject<Item> HAM_SOUP = REGISTRY.register("ham_soup", () -> new HamSoupItem());
	public static final RegistryObject<Item> LAMB_PLATE = REGISTRY.register("lamb_plate", () -> new LambPlateItem());
	public static final RegistryObject<Item> MANGO = REGISTRY.register("mango", () -> new MangoItem());
	public static final RegistryObject<Item> SWEAT_ROASTED_CHICKEN = REGISTRY.register("sweat_roasted_chicken", () -> new SweatRoastedChickenItem());
	public static final RegistryObject<Item> BANANA_SPLIT = REGISTRY.register("banana_split", () -> new BananaSplitItem());
	public static final RegistryObject<Item> CHILLI = REGISTRY.register("chilli", () -> new ChilliItem());
	public static final RegistryObject<Item> CHOCOLATE = REGISTRY.register("chocolate", () -> new ChocolateItem());
	public static final RegistryObject<Item> CHOCOLATE_STRAWBERRY = REGISTRY.register("chocolate_strawberry", () -> new ChocolateStrawberryItem());
	public static final RegistryObject<Item> COOKING_TABLE = block(ToamodModBlocks.COOKING_TABLE);
	public static final RegistryObject<Item> JADE_SWORD = REGISTRY.register("jade_sword", () -> new JadeSwordItem());
	public static final RegistryObject<Item> DEATHS_DANCE = REGISTRY.register("deaths_dance", () -> new DeathsDanceItem());
	public static final RegistryObject<Item> DRAGON_SLAYER = REGISTRY.register("dragon_slayer", () -> new DragonSlayerItem());
	public static final RegistryObject<Item> THE_DARK_BLADE = REGISTRY.register("the_dark_blade", () -> new TheDarkBladeItem());
	public static final RegistryObject<Item> ANCIENT_GUARDIAN_WARHAMMER = REGISTRY.register("ancient_guardian_warhammer", () -> new AncientGuardianWarhammerItem());
	public static final RegistryObject<Item> FLAME_SWORD = REGISTRY.register("flame_sword", () -> new FlameSwordItem());
	public static final RegistryObject<Item> LOG = block(ToamodModBlocks.LOG);
	public static final RegistryObject<Item> PURE_GOLD = REGISTRY.register("pure_gold", () -> new PureGoldItem());
	public static final RegistryObject<Item> PURE_IRON = REGISTRY.register("pure_iron", () -> new PureIronItem());
	public static final RegistryObject<Item> WOOD_ARMOR_HELMET = REGISTRY.register("wood_armor_helmet", () -> new WoodArmorItem.Helmet());
	public static final RegistryObject<Item> WOOD_ARMOR_CHESTPLATE = REGISTRY.register("wood_armor_chestplate", () -> new WoodArmorItem.Chestplate());
	public static final RegistryObject<Item> WOOD_ARMOR_LEGGINGS = REGISTRY.register("wood_armor_leggings", () -> new WoodArmorItem.Leggings());
	public static final RegistryObject<Item> WOOD_ARMOR_BOOTS = REGISTRY.register("wood_armor_boots", () -> new WoodArmorItem.Boots());
	public static final RegistryObject<Item> IRON_ARMOR_HELMET = REGISTRY.register("iron_armor_helmet", () -> new IronArmorItem.Helmet());
	public static final RegistryObject<Item> IRON_ARMOR_CHESTPLATE = REGISTRY.register("iron_armor_chestplate", () -> new IronArmorItem.Chestplate());
	public static final RegistryObject<Item> IRON_ARMOR_LEGGINGS = REGISTRY.register("iron_armor_leggings", () -> new IronArmorItem.Leggings());
	public static final RegistryObject<Item> IRON_ARMOR_BOOTS = REGISTRY.register("iron_armor_boots", () -> new IronArmorItem.Boots());
	public static final RegistryObject<Item> HARDENED_IRON_ARMOR_HELMET = REGISTRY.register("hardened_iron_armor_helmet", () -> new HardenedIronArmorItem.Helmet());
	public static final RegistryObject<Item> HARDENED_IRON_ARMOR_CHESTPLATE = REGISTRY.register("hardened_iron_armor_chestplate", () -> new HardenedIronArmorItem.Chestplate());
	public static final RegistryObject<Item> HARDENED_IRON_ARMOR_LEGGINGS = REGISTRY.register("hardened_iron_armor_leggings", () -> new HardenedIronArmorItem.Leggings());
	public static final RegistryObject<Item> HARDENED_IRON_ARMOR_BOOTS = REGISTRY.register("hardened_iron_armor_boots", () -> new HardenedIronArmorItem.Boots());
	public static final RegistryObject<Item> GOLD_ARMOR_HELMET = REGISTRY.register("gold_armor_helmet", () -> new GoldArmorItem.Helmet());
	public static final RegistryObject<Item> GOLD_ARMOR_CHESTPLATE = REGISTRY.register("gold_armor_chestplate", () -> new GoldArmorItem.Chestplate());
	public static final RegistryObject<Item> GOLD_ARMOR_LEGGINGS = REGISTRY.register("gold_armor_leggings", () -> new GoldArmorItem.Leggings());
	public static final RegistryObject<Item> GOLD_ARMOR_BOOTS = REGISTRY.register("gold_armor_boots", () -> new GoldArmorItem.Boots());
	public static final RegistryObject<Item> CRISTAL_ARMOR_HELMET = REGISTRY.register("cristal_armor_helmet", () -> new CristalArmorItem.Helmet());
	public static final RegistryObject<Item> CRISTAL_ARMOR_CHESTPLATE = REGISTRY.register("cristal_armor_chestplate", () -> new CristalArmorItem.Chestplate());
	public static final RegistryObject<Item> CRISTAL_ARMOR_LEGGINGS = REGISTRY.register("cristal_armor_leggings", () -> new CristalArmorItem.Leggings());
	public static final RegistryObject<Item> CRISTAL_ARMOR_BOOTS = REGISTRY.register("cristal_armor_boots", () -> new CristalArmorItem.Boots());
	public static final RegistryObject<Item> JADE_ARMOR_HELMET = REGISTRY.register("jade_armor_helmet", () -> new JadeArmorItem.Helmet());
	public static final RegistryObject<Item> JADE_ARMOR_CHESTPLATE = REGISTRY.register("jade_armor_chestplate", () -> new JadeArmorItem.Chestplate());
	public static final RegistryObject<Item> JADE_ARMOR_LEGGINGS = REGISTRY.register("jade_armor_leggings", () -> new JadeArmorItem.Leggings());
	public static final RegistryObject<Item> JADE_ARMOR_BOOTS = REGISTRY.register("jade_armor_boots", () -> new JadeArmorItem.Boots());
	public static final RegistryObject<Item> DRAGON_ARMOR_HELMET = REGISTRY.register("dragon_armor_helmet", () -> new DragonArmorItem.Helmet());
	public static final RegistryObject<Item> DRAGON_ARMOR_CHESTPLATE = REGISTRY.register("dragon_armor_chestplate", () -> new DragonArmorItem.Chestplate());
	public static final RegistryObject<Item> DRAGON_ARMOR_LEGGINGS = REGISTRY.register("dragon_armor_leggings", () -> new DragonArmorItem.Leggings());
	public static final RegistryObject<Item> DRAGON_ARMOR_BOOTS = REGISTRY.register("dragon_armor_boots", () -> new DragonArmorItem.Boots());
	public static final RegistryObject<Item> DEC_CRAFTING_TABLE = block(ToamodModBlocks.DEC_CRAFTING_TABLE);
	public static final RegistryObject<Item> DEC_BARREL_VERTICAL = block(ToamodModBlocks.DEC_BARREL_VERTICAL);
	public static final RegistryObject<Item> DEC_BARREL_HORIZONTAL = block(ToamodModBlocks.DEC_BARREL_HORIZONTAL);
	public static final RegistryObject<Item> DEC_ANVIL = block(ToamodModBlocks.DEC_ANVIL);
	public static final RegistryObject<Item> DEC_GRINDSTONE = block(ToamodModBlocks.DEC_GRINDSTONE);
	public static final RegistryObject<Item> DEC_GRINDSTONE_DOWN = block(ToamodModBlocks.DEC_GRINDSTONE_DOWN);
	public static final RegistryObject<Item> DEC_GRINDSTONE_SIDE = block(ToamodModBlocks.DEC_GRINDSTONE_SIDE);
	public static final RegistryObject<Item> RUNE_COMMAN = REGISTRY.register("rune_comman", () -> new RuneCommanItem());
	public static final RegistryObject<Item> RUNE_UNCOMMAN = REGISTRY.register("rune_uncomman", () -> new RuneUncommanItem());
	public static final RegistryObject<Item> RUNE_RARE = REGISTRY.register("rune_rare", () -> new RuneRareItem());
	public static final RegistryObject<Item> RUNE_EPIC = REGISTRY.register("rune_epic", () -> new RuneEpicItem());
	public static final RegistryObject<Item> RUNE_LEGENDARY = REGISTRY.register("rune_legendary", () -> new RuneLegendaryItem());
	public static final RegistryObject<Item> RUNE_MYTHIC = REGISTRY.register("rune_mythic", () -> new RuneMythicItem());
	public static final RegistryObject<Item> HORSE_CARE_TAKER_SPAWN_EGG = REGISTRY.register("horse_care_taker_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.HORSE_CARE_TAKER, -1, -10140895, new Item.Properties()));
	public static final RegistryObject<Item> RUNE_FRAGMENTS = REGISTRY.register("rune_fragments", () -> new RuneFragmentsItem());
	public static final RegistryObject<Item> FOOTLONG = REGISTRY.register("footlong", () -> new FootlongItem());
	public static final RegistryObject<Item> RAW_BEEF = REGISTRY.register("raw_beef", () -> new RawBeefItem());
	public static final RegistryObject<Item> COOKED_BEEF = REGISTRY.register("cooked_beef", () -> new CookedBeefItem());
	public static final RegistryObject<Item> TACO = REGISTRY.register("taco", () -> new TacoItem());
	public static final RegistryObject<Item> WARM_BREAKFAST = REGISTRY.register("warm_breakfast", () -> new WarmBreakfastItem());
	public static final RegistryObject<Item> SWEET_HAM = REGISTRY.register("sweet_ham", () -> new SweetHamItem());
	public static final RegistryObject<Item> RAW_HAM = REGISTRY.register("raw_ham", () -> new RawHamItem());
	public static final RegistryObject<Item> DWARFS_HYMN = REGISTRY.register("dwarfs_hymn", () -> new DwarfsHymnItem());
	public static final RegistryObject<Item> MYTHIC_RUNE_SCROLL = REGISTRY.register("mythic_rune_scroll", () -> new MythicRuneScrollItem());
	public static final RegistryObject<Item> CREATURE_BARRIER = block(ToamodModBlocks.CREATURE_BARRIER);
	public static final RegistryObject<Item> ENHANCMENT_TABLE = block(ToamodModBlocks.ENHANCMENT_TABLE);
	public static final RegistryObject<Item> MAGIC_CRAFTER = block(ToamodModBlocks.MAGIC_CRAFTER);
	public static final RegistryObject<Item> FORGER = block(ToamodModBlocks.FORGER);
	public static final RegistryObject<Item> GEMSTONE_RUBY = REGISTRY.register("gemstone_ruby", () -> new GemstoneRubyItem());
	public static final RegistryObject<Item> GEMSTONE_AMETHYST = REGISTRY.register("gemstone_amethyst", () -> new GemstoneAmethystItem());
	public static final RegistryObject<Item> GEMSTONE_TOPAZ = REGISTRY.register("gemstone_topaz", () -> new GemstoneTopazItem());
	public static final RegistryObject<Item> GEMSTONE_AQUAMARINE = REGISTRY.register("gemstone_aquamarine", () -> new GemstoneAquamarineItem());
	public static final RegistryObject<Item> GEMSTONE_AMBER = REGISTRY.register("gemstone_amber", () -> new GemstoneAmberItem());
	public static final RegistryObject<Item> GEMSTONE_TANZANITE = REGISTRY.register("gemstone_tanzanite", () -> new GemstoneTanzaniteItem());
	public static final RegistryObject<Item> GEMSTONE_EMERALD = REGISTRY.register("gemstone_emerald", () -> new GemstoneEmeraldItem());
	public static final RegistryObject<Item> GEMSTONE_PEARL = REGISTRY.register("gemstone_pearl", () -> new GemstonePearlItem());
	public static final RegistryObject<Item> GEMSTONE_OPAL = REGISTRY.register("gemstone_opal", () -> new GemstoneOpalItem());
	public static final RegistryObject<Item> GEMSTONE_DIAMOND = REGISTRY.register("gemstone_diamond", () -> new GemstoneDiamondItem());
	public static final RegistryObject<Item> GEMSTONE_SAPHIRE = REGISTRY.register("gemstone_saphire", () -> new GemstoneSaphireItem());
	public static final RegistryObject<Item> ENCH_BOOK = REGISTRY.register("ench_book", () -> new EnchBookItem());
	public static final RegistryObject<Item> BLACKSMITH_TABLE = block(ToamodModBlocks.BLACKSMITH_TABLE);
	public static final RegistryObject<Item> EMPTY_BOOK = REGISTRY.register("empty_book", () -> new EmptyBookItem());
	public static final RegistryObject<Item> HARD_STONE = block(ToamodModBlocks.HARD_STONE);
	public static final RegistryObject<Item> HARD_STONE_SLAB = block(ToamodModBlocks.HARD_STONE_SLAB);
	public static final RegistryObject<Item> GOBLIN_OMLETTE = block(ToamodModBlocks.GOBLIN_OMLETTE);
	public static final RegistryObject<Item> PLAYER_BARRIER = block(ToamodModBlocks.PLAYER_BARRIER);
	public static final RegistryObject<Item> PESTO_GOBLIN_OMLETTE = block(ToamodModBlocks.PESTO_GOBLIN_OMLETTE);
	public static final RegistryObject<Item> FRIED_GOBLIN_EGG = REGISTRY.register("fried_goblin_egg", () -> new FriedGoblinEggItem());
	public static final RegistryObject<Item> GOBLIN_EGG = REGISTRY.register("goblin_egg", () -> new GoblinEggItem());
	public static final RegistryObject<Item> GOBLIN_SPAWN_EGG = REGISTRY.register("goblin_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.GOBLIN, -10079488, -6737152, new Item.Properties()));
	public static final RegistryObject<Item> GUI_ITEM_GHOST_SPAWN_EGG = REGISTRY.register("gui_item_ghost_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.GUI_ITEM_GHOST, -1, -3355444, new Item.Properties()));
	public static final RegistryObject<Item> STARFALL_HYPERION = REGISTRY.register("starfall_hyperion", () -> new StarfallHyperionItem());
	public static final RegistryObject<Item> SCALDRIS_HYPERION = REGISTRY.register("scaldris_hyperion", () -> new ScaldrisHyperionItem());
	public static final RegistryObject<Item> COOKING_SKILL_ITEM = REGISTRY.register("cooking_skill_item", () -> new CookingSkillItemItem());
	public static final RegistryObject<Item> ARTEFACTS_ITEM = REGISTRY.register("artefacts_item", () -> new ArtefactsItemItem());
	public static final RegistryObject<Item> DARK_RED_DYE = REGISTRY.register("dark_red_dye", () -> new DarkRedDyeItem());
	public static final RegistryObject<Item> RED_GOBLIN_SCALE = REGISTRY.register("red_goblin_scale", () -> new RedGoblinScaleItem());
	public static final RegistryObject<Item> GOBLIN_EGG_SPICES = REGISTRY.register("goblin_egg_spices", () -> new GoblinEggSpicesItem());
	public static final RegistryObject<Item> BOSS_KEY_TIER_1 = REGISTRY.register("boss_key_tier_1", () -> new BossKeyTier1Item());
	public static final RegistryObject<Item> BOSS_KEY_TIER_2 = REGISTRY.register("boss_key_tier_2", () -> new BossKeyTier2Item());
	public static final RegistryObject<Item> BOSS_KEY_TIER_3 = REGISTRY.register("boss_key_tier_3", () -> new BossKeyTier3Item());
	public static final RegistryObject<Item> PLAYER_RECIPES_ITEM = REGISTRY.register("player_recipes_item", () -> new PlayerRecipesItemItem());
	public static final RegistryObject<Item> SUPER_ENCHANTMENT_BOOK = REGISTRY.register("super_enchantment_book", () -> new SuperEnchantmentBookItem());
	public static final RegistryObject<Item> PURE_CRYSTAL = REGISTRY.register("pure_crystal", () -> new PureCrystalItem());
	public static final RegistryObject<Item> POWER_CATALYST_1 = REGISTRY.register("power_catalyst_1", () -> new PowerCatalyst1Item());
	public static final RegistryObject<Item> POWER_CATALYST_2 = REGISTRY.register("power_catalyst_2", () -> new PowerCatalyst2Item());
	public static final RegistryObject<Item> POWER_CATALYST_3 = REGISTRY.register("power_catalyst_3", () -> new PowerCatalyst3Item());
	public static final RegistryObject<Item> POWER_CATALYST_4 = REGISTRY.register("power_catalyst_4", () -> new PowerCatalyst4Item());
	public static final RegistryObject<Item> POWER_CATALYST_5 = REGISTRY.register("power_catalyst_5", () -> new PowerCatalyst5Item());
	public static final RegistryObject<Item> STAT_ICON_HP = REGISTRY.register("stat_icon_hp", () -> new StatIconHPItem());
	public static final RegistryObject<Item> STAT_ICON_AR = REGISTRY.register("stat_icon_ar", () -> new StatIconARItem());
	public static final RegistryObject<Item> STAT_ICON_MR = REGISTRY.register("stat_icon_mr", () -> new StatIconMRItem());
	public static final RegistryObject<Item> STAT_ICON_AD = REGISTRY.register("stat_icon_ad", () -> new StatIconADItem());
	public static final RegistryObject<Item> STAT_ICON_MP = REGISTRY.register("stat_icon_mp", () -> new StatIconMPItem());
	public static final RegistryObject<Item> STAT_ICON_CRCD = REGISTRY.register("stat_icon_crcd", () -> new StatIconCRCDItem());
	public static final RegistryObject<Item> STAT_ICON_MF = REGISTRY.register("stat_icon_mf", () -> new StatIconMFItem());
	public static final RegistryObject<Item> STAT_ICON_MINF = REGISTRY.register("stat_icon_minf", () -> new StatIconMINFItem());
	public static final RegistryObject<Item> STAT_ICON_WIS = REGISTRY.register("stat_icon_wis", () -> new StatIconWISItem());
	public static final RegistryObject<Item> STAT_ICON_MANA = REGISTRY.register("stat_icon_mana", () -> new StatIconMANAItem());
	public static final RegistryObject<Item> ENCHANTMENT_BOOK = REGISTRY.register("enchantment_book", () -> new EnchantmentBookItem());
	public static final RegistryObject<Item> GOLD_BAR = REGISTRY.register("gold_bar", () -> new GoldBarItem());
	public static final RegistryObject<Item> IRON_BAR = REGISTRY.register("iron_bar", () -> new IronBarItem());
	public static final RegistryObject<Item> JADE_BAR = REGISTRY.register("jade_bar", () -> new JadeBarItem());
	public static final RegistryObject<Item> COAL_BAR = REGISTRY.register("coal_bar", () -> new CoalBarItem());
	public static final RegistryObject<Item> ILLFANGS_CUTLASS = REGISTRY.register("illfangs_cutlass", () -> new IllfangsCutlassItem());
	public static final RegistryObject<Item> CRYSTAL_SHARD = REGISTRY.register("crystal_shard", () -> new CrystalShardItem());
	public static final RegistryObject<Item> CRYSTAL = REGISTRY.register("crystal", () -> new CrystalItem());
	public static final RegistryObject<Item> CRYSTAL_CLUSTER = REGISTRY.register("crystal_cluster", () -> new CrystalClusterItem());
	public static final RegistryObject<Item> RED_CRYSTAL = REGISTRY.register("red_crystal", () -> new RedCrystalItem());
	public static final RegistryObject<Item> RED_CRYSTAL_CLUSTER = REGISTRY.register("red_crystal_cluster", () -> new RedCrystalClusterItem());
	public static final RegistryObject<Item> MITHRIL = REGISTRY.register("mithril", () -> new MithrilItem());
	public static final RegistryObject<Item> MITHRIL_BAR = REGISTRY.register("mithril_bar", () -> new MithrilBarItem());
	public static final RegistryObject<Item> RED_COPPER = REGISTRY.register("red_copper", () -> new RedCopperItem());
	public static final RegistryObject<Item> RED_COPPER_BAR = REGISTRY.register("red_copper_bar", () -> new RedCopperBarItem());
	public static final RegistryObject<Item> BLUE_COPPER = REGISTRY.register("blue_copper", () -> new BlueCopperItem());
	public static final RegistryObject<Item> BLUE_COPPER_BAR = REGISTRY.register("blue_copper_bar", () -> new BlueCopperBarItem());
	public static final RegistryObject<Item> INV_CONTROL_BARRIER = block(ToamodModBlocks.INV_CONTROL_BARRIER);
	public static final RegistryObject<Item> GOBLIN_SCOUT_SPAWN_EGG = REGISTRY.register("goblin_scout_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.GOBLIN_SCOUT, -6737152, -3394816, new Item.Properties()));
	public static final RegistryObject<Item> XEDRES_SPAWN_EGG = REGISTRY.register("xedres_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.XEDRES, -16777216, -6750208, new Item.Properties()));
	public static final RegistryObject<Item> GOBLIN_HUNTER_SPAWN_EGG = REGISTRY.register("goblin_hunter_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.GOBLIN_HUNTER, -16751104, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> TUSK = REGISTRY.register("tusk", () -> new TuskItem());
	public static final RegistryObject<Item> REFINED_TUSK = REGISTRY.register("refined_tusk", () -> new RefinedTuskItem());
	public static final RegistryObject<Item> DROP_OF_BLOOD = REGISTRY.register("drop_of_blood", () -> new DropOfBloodItem());
	public static final RegistryObject<Item> BURNING_SOUL = REGISTRY.register("burning_soul", () -> new BurningSoulItem());
	public static final RegistryObject<Item> MANA_STONE = REGISTRY.register("mana_stone", () -> new ManaStoneItem());
	public static final RegistryObject<Item> SMOOTH_ACACIA_PLANKS = block(ToamodModBlocks.SMOOTH_ACACIA_PLANKS);
	public static final RegistryObject<Item> SMOOTH_BIRCH_PLANKS = block(ToamodModBlocks.SMOOTH_BIRCH_PLANKS);
	public static final RegistryObject<Item> SMOOTH_CRIMSON_PLANKS = block(ToamodModBlocks.SMOOTH_CRIMSON_PLANKS);
	public static final RegistryObject<Item> SMOOTH_DARK_OAK_PLANKS = block(ToamodModBlocks.SMOOTH_DARK_OAK_PLANKS);
	public static final RegistryObject<Item> SMOOTH_JUNGLE_PLANKS = block(ToamodModBlocks.SMOOTH_JUNGLE_PLANKS);
	public static final RegistryObject<Item> SMOOTH_OAK_PLANKS = block(ToamodModBlocks.SMOOTH_OAK_PLANKS);
	public static final RegistryObject<Item> SMOOTH_WARPED_PLANKS = block(ToamodModBlocks.SMOOTH_WARPED_PLANKS);
	public static final RegistryObject<Item> SMOOTH_SPRUCE_PLANKS = block(ToamodModBlocks.SMOOTH_SPRUCE_PLANKS);
	public static final RegistryObject<Item> NPC_BLACKSMITH_1_SPAWN_EGG = REGISTRY.register("npc_blacksmith_1_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_BLACKSMITH_1, -10079488, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> NPC_BLACKSMITH_2_SPAWN_EGG = REGISTRY.register("npc_blacksmith_2_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_BLACKSMITH_2, -10079488, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> NPC_BLACKSMITH_3_SPAWN_EGG = REGISTRY.register("npc_blacksmith_3_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_BLACKSMITH_3, -10079488, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> NPC_BLACKSMITH_4_SPAWN_EGG = REGISTRY.register("npc_blacksmith_4_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_BLACKSMITH_4, -10079488, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> NPC_DWARF_1_SPAWN_EGG = REGISTRY.register("npc_dwarf_1_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_DWARF_1, -10079488, -3381760, new Item.Properties()));
	public static final RegistryObject<Item> NPC_DWARF_2_SPAWN_EGG = REGISTRY.register("npc_dwarf_2_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_DWARF_2, -10079488, -3381760, new Item.Properties()));
	public static final RegistryObject<Item> NPC_DWARF_3_SPAWN_EGG = REGISTRY.register("npc_dwarf_3_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_DWARF_3, -10079488, -3381760, new Item.Properties()));
	public static final RegistryObject<Item> NPC_DWARF_4_SPAWN_EGG = REGISTRY.register("npc_dwarf_4_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_DWARF_4, -10079488, -3381760, new Item.Properties()));
	public static final RegistryObject<Item> NPC_DWARF_5_SPAWN_EGG = REGISTRY.register("npc_dwarf_5_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_DWARF_5, -10079488, -3381760, new Item.Properties()));
	public static final RegistryObject<Item> NPC_DWARF_6_SPAWN_EGG = REGISTRY.register("npc_dwarf_6_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_DWARF_6, -10079488, -3381760, new Item.Properties()));
	public static final RegistryObject<Item> NPC_DWARF_7_SPAWN_EGG = REGISTRY.register("npc_dwarf_7_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_DWARF_7, -10079488, -3381760, new Item.Properties()));
	public static final RegistryObject<Item> NPC_DWARF_8_SPAWN_EGG = REGISTRY.register("npc_dwarf_8_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_DWARF_8, -10079488, -3381760, new Item.Properties()));
	public static final RegistryObject<Item> NPC_FAIRY_1_SPAWN_EGG = REGISTRY.register("npc_fairy_1_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_FAIRY_1, -6750055, -39169, new Item.Properties()));
	public static final RegistryObject<Item> NPC_FAIRY_2_SPAWN_EGG = REGISTRY.register("npc_fairy_2_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_FAIRY_2, -6750055, -39169, new Item.Properties()));
	public static final RegistryObject<Item> NPC_FAIRY_3_SPAWN_EGG = REGISTRY.register("npc_fairy_3_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_FAIRY_3, -6750055, -39169, new Item.Properties()));
	public static final RegistryObject<Item> NPC_FEMALE_1_SPAWN_EGG = REGISTRY.register("npc_female_1_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_FEMALE_1, -6737152, -13408768, new Item.Properties()));
	public static final RegistryObject<Item> NPC_FEMALE_2_SPAWN_EGG = REGISTRY.register("npc_female_2_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_FEMALE_2, -6737152, -13408768, new Item.Properties()));
	public static final RegistryObject<Item> NPC_FEMALE_3_SPAWN_EGG = REGISTRY.register("npc_female_3_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_FEMALE_3, -6737152, -13408768, new Item.Properties()));
	public static final RegistryObject<Item> NPC_FEMALE_4_SPAWN_EGG = REGISTRY.register("npc_female_4_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_FEMALE_4, -6737152, -13408768, new Item.Properties()));
	public static final RegistryObject<Item> NPC_FEMALE_5_SPAWN_EGG = REGISTRY.register("npc_female_5_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_FEMALE_5, -6737152, -13408768, new Item.Properties()));
	public static final RegistryObject<Item> NPC_FEMALE_6_SPAWN_EGG = REGISTRY.register("npc_female_6_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_FEMALE_6, -6737152, -13408768, new Item.Properties()));
	public static final RegistryObject<Item> NPC_FEMALE_7_SPAWN_EGG = REGISTRY.register("npc_female_7_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_FEMALE_7, -6737152, -13408768, new Item.Properties()));
	public static final RegistryObject<Item> NPC_FEMALE_8_SPAWN_EGG = REGISTRY.register("npc_female_8_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_FEMALE_8, -6737152, -13408768, new Item.Properties()));
	public static final RegistryObject<Item> NPC_KNIGHT_1_SPAWN_EGG = REGISTRY.register("npc_knight_1_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_KNIGHT_1, -13421773, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> NPC_KNIGHT_2_SPAWN_EGG = REGISTRY.register("npc_knight_2_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_KNIGHT_2, -13421773, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> NPC_KNIGHT_3_SPAWN_EGG = REGISTRY.register("npc_knight_3_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_KNIGHT_3, -13421773, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> NPC_KNIGHT_4_SPAWN_EGG = REGISTRY.register("npc_knight_4_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_KNIGHT_4, -13421773, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> NPC_KNIGHT_5_SPAWN_EGG = REGISTRY.register("npc_knight_5_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_KNIGHT_5, -13421773, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> NPC_KNIGHT_6_SPAWN_EGG = REGISTRY.register("npc_knight_6_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_KNIGHT_6, -13421773, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MALE_1_SPAWN_EGG = REGISTRY.register("npc_male_1_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MALE_1, -10079488, -16737793, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MALE_2_SPAWN_EGG = REGISTRY.register("npc_male_2_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MALE_2, -10079488, -16737793, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MALE_3_SPAWN_EGG = REGISTRY.register("npc_male_3_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MALE_3, -10079488, -16737793, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MALE_4_SPAWN_EGG = REGISTRY.register("npc_male_4_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MALE_4, -10079488, -16737793, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MALE_5_SPAWN_EGG = REGISTRY.register("npc_male_5_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MALE_5, -10079488, -16737793, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MALE_6_SPAWN_EGG = REGISTRY.register("npc_male_6_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MALE_6, -10079488, -16737793, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MALE_7_SPAWN_EGG = REGISTRY.register("npc_male_7_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MALE_7, -10079488, -16737793, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MALE_8_SPAWN_EGG = REGISTRY.register("npc_male_8_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MALE_8, -10079488, -16737793, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MALE_9_SPAWN_EGG = REGISTRY.register("npc_male_9_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MALE_9, -10079488, -16737793, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MINER_2_SPAWN_EGG = REGISTRY.register("npc_miner_2_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MINER_2, -10066330, -13312, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MINER_3_SPAWN_EGG = REGISTRY.register("npc_miner_3_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MINER_3, -10066330, -13312, new Item.Properties()));
	public static final RegistryObject<Item> NPC_ROYAL_COMMANDER_SPAWN_EGG = REGISTRY.register("npc_royal_commander_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_ROYAL_COMMANDER, -10079488, -10092544, new Item.Properties()));
	public static final RegistryObject<Item> NPC_COPPER_MINER_SPAWN_EGG = REGISTRY.register("npc_copper_miner_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_COPPER_MINER, -39424, -16724839, new Item.Properties()));
	public static final RegistryObject<Item> NPC_DUNGEON_MASTER_SPAWN_EGG = REGISTRY.register("npc_dungeon_master_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_DUNGEON_MASTER, -10092544, -3355444, new Item.Properties()));
	public static final RegistryObject<Item> NPC_FOREIGN_MERCHANT_SPAWN_EGG = REGISTRY.register("npc_foreign_merchant_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_FOREIGN_MERCHANT, -16751053, -3381760, new Item.Properties()));
	public static final RegistryObject<Item> NPC_GOLDEN_KNIGHT_SPAWN_EGG = REGISTRY.register("npc_golden_knight_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_GOLDEN_KNIGHT, -13312, -65536, new Item.Properties()));
	public static final RegistryObject<Item> NPC_HUNTER_SPAWN_EGG = REGISTRY.register("npc_hunter_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_HUNTER, -6724096, -1, new Item.Properties()));
	public static final RegistryObject<Item> NPC_IRON_GOLEM_SPAWN_EGG = REGISTRY.register("npc_iron_golem_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_IRON_GOLEM, -13421773, -1, new Item.Properties()));
	public static final RegistryObject<Item> NPC_JAEDUS_SPAWN_EGG = REGISTRY.register("npc_jaedus_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_JAEDUS, -13421773, -16724890, new Item.Properties()));
	public static final RegistryObject<Item> NPC_LUMBERJACK_SPAWN_EGG = REGISTRY.register("npc_lumberjack_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_LUMBERJACK, -10079488, -16750900, new Item.Properties()));
	public static final RegistryObject<Item> NPC_LOST_ADVENTURER_SPAWN_EGG = REGISTRY.register("npc_lost_adventurer_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_LOST_ADVENTURER, -10079488, -16750900, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MAXOR_SPAWN_EGG = REGISTRY.register("npc_maxor_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MAXOR, -13421773, -3381505, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MIST_MAGE_SPAWN_EGG = REGISTRY.register("npc_mist_mage_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MIST_MAGE, -12633533, -734652, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MIST_MERCHANT_SPAWN_EGG = REGISTRY.register("npc_mist_merchant_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MIST_MERCHANT, -16770741, -734652, new Item.Properties()));
	public static final RegistryObject<Item> NPC_NECRON_SPAWN_EGG = REGISTRY.register("npc_necron_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_NECRON, -13421773, -1086426, new Item.Properties()));
	public static final RegistryObject<Item> NPC_NECROTIC_KNIGHT_SPAWN_EGG = REGISTRY.register("npc_necrotic_knight_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_NECROTIC_KNIGHT, -13421773, -2829100, new Item.Properties()));
	public static final RegistryObject<Item> NPC_PHANTOM_SPAWN_EGG = REGISTRY.register("npc_phantom_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_PHANTOM, -13421773, -15200744, new Item.Properties()));
	public static final RegistryObject<Item> NPC_PRIATE_CAPTAIN_SPAWN_EGG = REGISTRY.register("npc_priate_captain_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_PRIATE_CAPTAIN, -13395457, -4109056, new Item.Properties()));
	public static final RegistryObject<Item> NPC_ROYAL_KNIGHT_SPAWN_EGG = REGISTRY.register("npc_royal_knight_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_ROYAL_KNIGHT, -9868951, -5963776, new Item.Properties()));
	public static final RegistryObject<Item> NPC_SLEEPY_SCORPIUS_SPAWN_EGG = REGISTRY.register("npc_sleepy_scorpius_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_SLEEPY_SCORPIUS, -16737895, -2039584, new Item.Properties()));
	public static final RegistryObject<Item> NPC_STORM_SPAWN_EGG = REGISTRY.register("npc_storm_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_STORM, -13421773, -16724788, new Item.Properties()));
	public static final RegistryObject<Item> NPC_WARDEN_KNIGHT_SPAWN_EGG = REGISTRY.register("npc_warden_knight_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_WARDEN_KNIGHT, -14802913, -16751002, new Item.Properties()));
	public static final RegistryObject<Item> EMPHEIAS_SOUL = block(ToamodModBlocks.EMPHEIAS_SOUL);
	public static final RegistryObject<Item> BOSS_ILLFANG_SPAWN_EGG = REGISTRY.register("boss_illfang_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.BOSS_ILLFANG, -10092544, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> NPC_MERCHANT_SPAWN_EGG = REGISTRY.register("npc_merchant_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MERCHANT, -13421569, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> RESPAWN_ORE = block(ToamodModBlocks.RESPAWN_ORE);
	public static final RegistryObject<Item> MITHRIL_ORE = block(ToamodModBlocks.MITHRIL_ORE);
	public static final RegistryObject<Item> NPC_MINER_1_SPAWN_EGG = REGISTRY.register("npc_miner_1_spawn_egg", () -> new ForgeSpawnEggItem(ToamodModEntities.NPC_MINER_1, -10066330, -13312, new Item.Properties()));
	public static final RegistryObject<Item> MITHRIL_SWORD = REGISTRY.register("mithril_sword", () -> new MithrilSwordItem());
	public static final RegistryObject<Item> ROUGH_RUNE_FRAGMENT = REGISTRY.register("rough_rune_fragment", () -> new RoughRuneFragmentItem());
	public static final RegistryObject<Item> FLAWED_RUNE_FRAGMENT = REGISTRY.register("flawed_rune_fragment", () -> new FlawedRuneFragmentItem());
	public static final RegistryObject<Item> FINE_RUNE_FRAGMENT = REGISTRY.register("fine_rune_fragment", () -> new FineRuneFragmentItem());
	public static final RegistryObject<Item> FLAWLESS_RUNE_FRAGMENT = REGISTRY.register("flawless_rune_fragment", () -> new FlawlessRuneFragmentItem());
	public static final RegistryObject<Item> PRISTINE_RUNE_FRAGMENT = REGISTRY.register("pristine_rune_fragment", () -> new PristineRuneFragmentItem());
	public static final RegistryObject<Item> EXQUISITE_RUNE_FRAGMENT = REGISTRY.register("exquisite_rune_fragment", () -> new ExquisiteRuneFragmentItem());
	public static final RegistryObject<Item> NEAR_PERFECT_RUNE_FRAGMENT = REGISTRY.register("near_perfect_rune_fragment", () -> new NearPerfectRuneFragmentItem());
	public static final RegistryObject<Item> PERFECT_RUNE_FRAGMENT = REGISTRY.register("perfect_rune_fragment", () -> new PerfectRuneFragmentItem());
	public static final RegistryObject<Item> BOSS_KEY_TIER_4 = REGISTRY.register("boss_key_tier_4", () -> new BossKeyTier4Item());
	public static final RegistryObject<Item> BOSS_KEY_TIER_5 = REGISTRY.register("boss_key_tier_5", () -> new BossKeyTier5Item());
	public static final RegistryObject<Item> CONDENSED_IRON_BLOCK = block(ToamodModBlocks.CONDENSED_IRON_BLOCK);
	public static final RegistryObject<Item> HARDENED_IRON_SWORD = REGISTRY.register("hardened_iron_sword", () -> new HardenedIronSwordItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
